<?php include('../header.php');?>
      <div class="row">
        <div class="large-9 columns" role="content">
          <!-- AthleteFoot -->
          <a name="dermotological"></a>
          <h2>Dermotological Care</h2>
          <hr/>
          <article>
            <h3><a name="AthleteFoot" data-magellan-destination="AthleteFoot"></a>Athlete's Foot</h3>
            <h5>Written by <a href="#">John Smith</a> on August 12, 2012.</h5>
              <div class="large-12 columns">
                <p>Athlete's foot is the most common term to describe a fungus condition involving the skin of the feet and toes. Another term is Tinea Pedis. A more appropriate name is Dermatophytosis. The three names above really mean the same thing. The patient first notices an itching sensation, usually between the toes. The skin in that area may have small blisters and be peeling. A less itchy form of Athlete's Foot can appear as a dry, red peeling condition on the bottom of the foot. The skin may be red with scaling and there may be small blisters containing a sticky, clear fluid around the area. The skin may have a stinging or burning feeling. The area between toes may show peeling with cracks and redness and maceration (moist, white wrinkled area). Generally there is considerable itching.
                </p>
                <h5>Causes</h5>
                <p>The fungi organisms that cause Athlete's Foot are microscopic and grow like small plants, surviving on the protein called keratin in dead skin. The source of the fungus is usually from the soil, an animal such as a dog, cat or rodent, or possibly from another person. Many people actually have the fungus on their skin but unless certain conditions are present, athlete's foot will not develop. These conditions include injury such as bruising or breaks in the skin. Areas of the body where moisture accumulates favor growth of these organisms, like between the 4th and 5th toes. The fungi thrive in a dark, warm, moist environment, which is often the case inside our shoes and socks. People who go barefoot all the time have little or no incidence of this problem. We don't know why some people develop this problem and others do not. Many times only one member of a family will have dermatophytosis, even though bathrooms and showers are shared. There may well be an individual predisposition to develop it.</p>
                <h5>What can I do for it?</h5>
                <p>At home, dust anti-fungal powders in your socks and shoes every day. Apply an over the counter cream two to three times daily. Wash canvas shoes frequently and change socks at least every day. People with diabetes or circulatory problems should take especially good care of their feet. If it persists over two weeks, consult your podiatric physician.</p>
                <h5>Prevention</h5>
                <p>The best offense is a good defense! Use powder in shoes and socks. Do not wear synthetic or nylon socks that trap perspiration. Wear cotton to absorb moisture . Dry feet thoroughly, particularly between toes (consider a hair drier on low heat). Change socks and wash shoes periodically. Use your topical medicine and if it doesn't improve, check with your foot and ankle specialist right away.</p>
              </div>
          </article>

          <hr/>
          <!--  FungusNails -->
          <article>
            <h3><a name="FungusNails" data-magellan-destination="FungusNails"></a>Fungus Nails</h3>
            <div class="large-12 columns">
              <h5>Description</h5>
              <p>One of the more common conditions treated by podiatric surgeonsis the painful bunion. Patients with this condition will usually complain of pain when wearing certain shoes, especially snug fitting dress shoes, or with physical activity, such as walking or running. Bunions are most commonly treated by conservative means. This may involve shoe gear modification, padding and <a target="_blank" href="http://www.podiatrynetwork.com/document_disorders.cfm?id=148">orthoses</a>. When this fails to provide adequate relief, surgery is often recommended. There are several surgical procedures to correct bunions. Selection of the most appropriate procedure for each patient requires knowledge of the level of deformity, review of the x-rays and an open discussion of the goals of the surgical procedure. Almost all surgical procedures require cutting and repositioning the first <strong>metatarsal</strong>.                  <img algin="right" src="../img/fungal.jpg"/>
</p>
              <h5>Cause of Bunion Deformity</h5>
              <p>The classic bunion, medically known as <strong>hallux abducto valgus</strong> or <strong>HAV</strong>,is a bump on the side of the great toe joint. This bump represents an actual deviation of the 1st metatarsal and often an overgrowth of bone on the metatarsal head. In addition, there is also deviation of the great toe toward the second toe. In severe cases, the great toe can either lie above or below the second toe. Shoes are often blamed for creating these problems. This, however, is inaccurate. It has been noted that primitive tribes where going barefoot is the norm will also develop bunions. Bunions develop from abnormal foot structure and bio-mechanics (e.g. excessive <strong>pronation</strong>), which place an undue load on the 1st metatarsal. This leads to stretching of supporting soft tissue structures such as joint capsules and ligaments with the end result being gradual deviation of the 1st metatarsal. As the deformity increases, there is an abnormal pull of certain tendons, which leads to the drifting of the great toe toward the 2nd toe. At this stage, there is also adaptation of the joint itself that occurs. Bunions tend to be familial but not hereditary.</p>
              <h5>Symptoms Related to Bunion Deformity </p>
              <p>The most common symptoms associated with this condition are pain on the side of the foot. Shoes will typically aggravate bunions. Stiff leather shoes or shoes with a tapered <strong>toe box</strong> are the prime offenders. This is why bunion pain is most common in women whose shoes have a pointed toe box. The bunion site will often be slightly swollen and red from the constant rubbing and irritation of a shoe. Occasionally, corns can develop between the 1st and 2nd toe from the pressure the toes rubbing against each other. On rare occasions, the joint itself can be acutely inflamed from the development of a sac of fluid over the bunion called a bursa. This is designed to protect and cushion the bone. However, it can become acutely inflamed, a condition referred to as <strong>bursitis.</strong></p>
              <h5>Treatment of Bunion Deformity</h5>
              <p>Early treatment of bunions is centered on providing symptomatic relief. Switching to a shoe with a rounder, deeper toe box and made of a softer more pliable leather will often provide immediate relief. The use of pads and cushions to reduce the pressure over the bone can also be helpful for mild bunion deformities. Controlling abnormal pronation, by the use of Orthotics and ther by reduces the deforming forces leading to bunions in the first place is usually the initial treatment of choice. These may help reduce pain in mild bunion deformities and slow the progression of the deformity. When these conservative measures fail to provided adequate relief, surgical correction is indicated. The choice of surgical procedures (<strong>bunionectomy</strong>) is based on a biomechanical and radiographic examination of the foot. Because there is actual bone displacement and joint adaptation, most successful bunionectomies require cutting and realigning the 1st metatarsal (an <strong>osteotomy</strong>). Simply "shaving the bump" is often inadequate in providing long-term relief of symptoms and in some cases can actually cause the bunion to progress faster. The most common procedure performed for the correction of bunions is the osteotomy near the level of the joint.</p>
            </div>
          </article>

          <hr/>
          <!-- PlantarWarts -->
          <article>
            <h3><a name="PlantarWarts" data-magellan-destination="PlantarWarts"></a>Plantar Warts</h3>
            <div class="large-12 columns">
              <h5>What's the problem?</7>
              <p>A plantar wart is a small skin lesion that resembles a callus and is found on the bottom of the foot or toes. The term "plantar" doesn't mean only farmers get them. "Plantar" means they occur on the bottom surface of the foot. It is usually under 1 cm diameter, but can occur in clusters and be much larger. Sometimes a single larger wart is surrounded by many smaller warts. In this case, they are called mosaic warts. Warts are more prevalent in young adults.</p>
              <h5>SYMPTOMS </p>
              <p>A plantar wart feels like a lump under the foot. They are only painful if queezed or pinched from side to side, or if you bear direct weight on them. Warts on other parts of the body, such as the hands, grow elevated above the skin's surface. We bear weight on warts on the bottom of the foot, so they get flattened and pushed into the skin. Most people liken this to walking with a rock attached to the foot, as the thickened callous tissue becomes hard and painful as it gets bigger. A plantar wart can usually be diagnosed by your doctor based on a characteristic appearance alone. When the doctor trims the hard callus tissue from the surface of the wart, a pattern of small black dots that are actually small blood vessels that feed the wart, is usually seen. The doctor will also test the wart by pressing directly down on it, and then pinching it, squeezing it from side to side. Most warts won't hurt when pressed directly down, but are very painful when pinched. If these findings are present, no further testing is necessary to identify a plantar wart.</p>
              <h5>Etiology</h5>
              <p>All warts are caused by the Papilloma virus, a slow growing virus which invades the skin. The viruses are common in all of our environments and they don't readily grow on intact skin. But if there is a break in the skin, such as a scratch or thorn penetration, this gives the virus the opportunity to get in and start growing. The virus only grows in the epidermis, the thick layer of the skin closest to the surface. It doesn't invade the dermis, the deeper layer of the skin. However, the epidermis and the dermis are closely entwined, and the dermis under the wart grows extra blood vessels and nerves in response to the virus infected cells above it in the epidermis. It is because of these nerves that the wart hurts when pinched and because of these blood vessels that it stays well nourished enough to grow. The virus particles can spread from the main wart, along the cutaneous (skin) nerves, to begin growing remote or satellite warts at a distance from the original site. If enough of this spread occurs, mosaic warts result.</p>
              <h5>Treatment</h5>
              <p>Over the counter products that contain the ingredient salicylic acid may be tried if you have good blood flow, good feeling in your feet, and the wart is small. However, their use is slow and frustrating. They are acids which slowing destroy the wart from the surface down. Diabetics or other people with numbness or bad circulation should not use these products, as it can cause ulceration. Your doctor has a number of choices for treating your Plantar Wart. Unfortunately, warts are stubborn entities and even the best methods for removing them allow a high rate of reoccurrence, around 15%. . Depending on the size and number of warts, treatment can take from 1-4 months before the wart is completely gone, and like any infection, all parts of it must be completely eliminated, or it will grow back. An additional option is to physically remove the wart at one time, either surgically, or with the CO2 laser. The healing time is from 2-4 weeks, depending on the size. Use of the CO2 laser reduces the rate of reoccurrence to 10%, reduces post-operative pain and eliminates any bleeding.</p>
            </div>
          </article>

          <hr/>
          <!-- Ulcers -->
          <article>
            <h3><a name="Ulcers" data-magellan-destination="Ulcers"></a>Ulcers</h3>
              <div class="large-12 columns">
              <h5>What's the problem?</7>
              <p>When using the term ulcer, we are generally referring to breaks in the normal integrity of the skin. Ulcers are skin wounds that are slow to heal and are classified in four stages, according to which layers of skin are broken through.</p>
              <p>Stage 1 ulcers are characterized by a reddening over bony areas. The redness on the skin does not go away when pressure is relieved.</p>
              <p>Stage 2 ulcers are characterized by blisters, peeling or cracked skin. There is a partial thickness skin loss involving the top two layers of the skin.</p>
              <p>Stage 3 ulcers are characterized by broken skin and sometimes bloody drainage. There is a full thickness skin loss involving subcutaneous tissue (the tissue between the skin and the muscle.)</p>
              <p>Stage 4 ulcers are characterized by breaks in the skin involving skin, muscle, tendon and bone and are often associated with a bone infection called osteomyelitis.</p>
              <h5>How does it feel?</h5>
              <p>How an ulcer feels is dependent on the underlying cause of the ulcer. For example,one of the more common types of ulcers is seen in patients with diabetes, who have loss of sensation in their feet. In this type of ulcer, there is little if any pain, due to a condition called diabetic neuropathy. In fact, diabetics typically get this type of ulcer because they've lost their protective pain sensation. Another common ulcer is due to loss of arterial blood flow to the leg, resulting in ischemic ulcers that can be very painful.</p>
              <p>So you can see that it very important to have any break in the skin properly evaluated and the lack of pain is not always a good initiator as to the severity of the problem.</p>
              <h5>Let's do a test!<h5>
              <p>There are many different diagnostic tests that can be done in the course of treating an ulcer. If the ulcer appears to be infected, i.e., there is redness, and drainage, then a culture of the wound should be done. The reason for the culture is to identify the type of infection, so that you can be put on the appropriate antibiotic. If there is suspicion of the bone being infected under the ulcer, the doctor will do x-rays and/or a bone scan. If there is suspicion that the underlying reason for the ulcer is poor circulation, then a non-invasive vascular study can be done. This test is to see if you have enough oxygen getting down to the area to heal the ulcer.</p>
              <h5>How did this happen?</h5>
              <p> Ulcers occur due to different reasons, so it is very important to determine the underlying medical problem that caused the ulcer. There are essentially four main reasons people get ulcers on the foot.</p>
              <p><em>Neuropathic:</em> This is when a patient has loss of sensation in the feet. It is commonly seen in people with diabetes but it can be caused by other reasons such as chronic alcohol abuse. These ulcers are generally seen under weight bearing areas and often will begin as a callus or a corn.</p>
              <p><em>Arterial:</em> This type of ulcer is due to poor blood flow to the lower extremity. This type of ulcer can be very painful and are usually found on the tips of toes, lower legs, ankle, heel and top of the foot. They can very easily become infected.</p>
              <p><em>Venous:</em> This type of ulcer is due to compromised veins. Veins are the vessels that take fluid out of the legs and back up to the heart. Veins have small valves that allow blood to flow only one way, back up to the heart. The valves normally block the tendency for gravity to pull the blood back down to the legs. Sometimes the valves leak or cease to work at all. If the valves do not work, then the fluid pools down in the legs, causing swelling. This swelling leads to increase pressure in the venous system, producing discoloration of the leg and eventually this lead to ulceration. They are commonly seen around the inside of the ankle and are slow to heal.</p>
              <p><em>Decubitus:</em> This type of ulcer is caused by excessive prolonged pressure on one area of the foot. The most common place to see this type of ulcer is in a person confined to bed and they occur on the backs of the heels.</p>
              <h5>What can I do for it?</h5>
              <p>The best thing you can do for an ulcer is to have it looked at by your doctor, as soon as you can. The earlier that the ulcer is treated, the better chance you have at healing it.</p>
              <h5>What will my doctor do for it?</h5>
              <p>The first thing that will be done is to inspect the wound. The doctor is lookingfor signs of infection, location of the wound, the color of the tissue in the wound. This is all done to determine the best treatment for that wound. Often the doctor will refer you to another specialist, such as a vascular doctor, to check your circulation. If you are a diabetic, he will want to consult with your diabetes doctor, to make sure that your blood sugar is under control. Once the cause of the ulcer is determined and all the necessary referrals are made, treatment of the ulcer can begin. The treatment will be tailored to the individual ulcer and it is often difficult to predict how long it will take an ulcer to heal. Ulcer care is best treated by a team approach, involving a few different types of doctors.</p>
              <h5>Can I prevent it from happening again?</p>
              <p>Yes. The best prevention is treating the underlying cause of the ulcer. That means if you are a diabetic, check your blood sugar daily and inspect your feet every day. If the reason for your ulcer is due to swelling in the legs, then you need to wear support stockings and keep your feet elevated as much as possible.</p>
              <p>Ulcers can be a very debilitating problem, causing pain and disability. The best treatment is preventing the ulcer from ever occurring. If it does occur, have it checked immediately by your doctor.</p>
              </div>
          </article>

          <hr/>
          <!-- CornsCalluses -->
          <article>
            <h3><a name="CornsCalluses" data-magellan-destination="CornsCalluses"></a>Corns and Calluses</h3>
            <div class="large-12 columns">
              <p>A corn is simply an area of hard, thickened skin that can occur on the top, between, or on the tip of the toes. A callus is similar in nature, but is larger and usually occurs across the ball of the foot, on the heel, or on the outer side of the great toe. Corns and calluses are often mistakenly considered a "skin" condition. They are actually the visible sign of an underlying "bone" problem.</p>
              <h5>Treatment</h5>
              <p>First, your doctor will conduct a thorough inspection of these areas. He/she may gently trim some of the thickened skin away, in order to rule out a wart (caused by a viral infection of the skin) as the culprit. X-rays will often be taken to identify the specific bone problem that is causing the corn or callus. The doctor may place a small marker on the corn before taking the x-ray, to make it's location visible on the x-ray. The finished x-ray will then show the location of the corn and the bone spur underneath that caused it.</p>
              <h5>HOW DID THIS HAPPEN?</h5>
              <p>Corns and calluses form due bodys way of protecting itself from repeated friction and ecess pressure. This is usually as a result of shoe (or ground) rubs against a bony prominence (bone spur) on the toe or foot. The skin thickens in response to this pressure, in order to protect the area from developing an open sore or blister. Small amounts of friction or pressure over long periods of time cause a corn or callus. Corns can be due to a buckled or contracted toe position called a hammer toe. Corns and calluses on the bottom of the foot are often caused by a plantar flexion of the metatarsal. This caused the metatarsal head (the long bone that forms the ball of the foot) to carry more than its fair share of the body weight causing excess pressure. A poor choice of shoes can aggravate corns and calluses, but often it is not the only cause. REMEMBER A BAD FOOT CAN NOT BE FIXED BY A GOOD SHOE, BUT A GOOD FOOT CAN BE RUINED BY A BAD SHOE. </p>
              <h5>Treatment</h5>
              <p>Trimming of this thick skin can relieve the pressure for a short time. You should never consider doing this yourself if you are diabetic or have poor circulation. If you cut yourself, you may cause an infection. Corn pads and callus removers often have harsh acids that peel this excess skin away after repeated application, but they can cause a severe chemical burn BUT WILL NOT CORRECT THE UNDERLYINBG CAUSE OF THE CORNS. This might lead to infection and greater pain than the original foot condition....so do not use any "corn removers". A pumice stone, buff bar or emery board can be used to "file" this thickened skin. This should be done gradually, a bit at time, ideally after each shower or bath. Attempting to file off the entire thickness of a corn or callus can result in a burn or abrasion. Applying a good moisturizer to the hardened areas should keep them softer and relieve pain. Non-medicated corn pads or moleskin (a thin fuzzy sheet of fabric with an adhesive back) can be purchased to protect corns and calluses, but should be removed carefully, so you do not tear the skin, and should only be worn for a day at a time.</p>
              <h5>Treatment</h5>
              <p>After an initial history and physical exam of your feet, x-rayswill be needed to tell the whole story and determine why corns and calluses are developing. Your doctor is the expert in trimming down these areas of thick skin and will often apply comfortable padding to these painful corns and calluses. Changes in shoe wear may be recommended. A prescription custom-made device called an orthotic might be made to wear inside your shoes, to redistribute pressure more evenly across the ball of your foot. A pad placed in your shoes (called a metatarsal pad) may help reduce your contracted hammer toes and relieve pressure on the ball of the foot as well. Often corns and calluses will have to be trimmed on a regular basis to prevent them from hurting. Eventually, you may desire corrective foot surgery by your podiatrist to straighten curled or contracted toes for corns or elevate and shorten metatarsals for calluses. Often such surgery represents a short term inconvenience to your lifestyle, but will not require any lengthy period of rest or inactivity. Many satisfied patients have remarked that surgery to remove the bone beneath the corn hurts less the very next day than on a painful day walking in their shoes with the corn present.</p>
              <h5>Prevention</h5>
              <p>Often changing your style or size of shoes may help. Carefully review the shoes in your closet. Check their fit and discard any that have seams and stitching over painful corns or have worn out innersoles that offer too little protection for calluses on the ball and heel of your foot.</p>
              <p>Make sure shoes are wide enough for your feet and have enough depthin the toe area to allow minimal pressure on the toes. To demonstrate whether your shoes are of adequate size and shape, place your foot on a blank sheet of paper and trace the shape of your foot. Then, place the shoe in question on top of your foot tracing. You may be surprised, as are many people, that your shoes are actually smaller and narrower than your feet. Try to imagine the forces present in that shoe when you squeeze your foot into it and then walk at any speed. Ouch! Review the socks in your drawer. If they have thick seams at the toes or holes, it's time to go shopping. Try to choose natural materials such as cotton and wool. Several types of socks (such as Thor-lo brand) have a double thickness in the toes and heels to protect these areas. Nylon hose can be purchased that have a woven cotton sole on the bottom of the foot to offer less friction and more padding. Corns and calluses almost always persist until corrective surgical measures are taken, so don't become discouraged if your efforts to prevent them are less than successful.</p>
            </div>
          </article>
          <!-- IngrownToenails -->
          <article>
            <h3><a name="IngrownToenails" data-magellan-destination="IngrownToenails"></a>Ingrown Toenail (Onychocryptosis)</h3>
              <div class="large-12 columns">
                <p>An ingrown nail occurs when a portion of a toenail on either side of the toe turns downward and presses into the skin. Nails normally are nearly flat, with just a slight arcing downward at the borders. When the border of the nail is turned downward, it begins to injure the skin. Patient's usually feel pressure and eventually pain, as the hard and sharp nail edge creates further injury. Shoes that apply pressure to the toe increase the pain. If an infection develops, the pain becomes intolerable. <img algin="right" src="../img/ingrown.jpg"/></p>
                <h5>Etiology</p>
                <p>A progression of events occurs. Routinely cutting the nails improperly, down at an angle instead of straight across, is the most common cause of Ingrown Nails. Wearing narrow or pointed shoes can apply enough pressure to a normal nail to turn the nail edge downward. Once the nail matrix, the tissue where the nail grows from, gets injured in this way, it continues to produce a nail edge that is more vertical than horizontal. From this abnormal nail growth, the nail edge applies mild pressure on the skin over a long period of time. The skin at the nail edge thickens and becomes hardened. You may begin to notice an enlargement or swelling of the skin around the nail edge. This can be accompanied by an increase in pain. The condition can progress as a result of other factors. These factors include: pressure from a tight or pointed shoe, injury such as stubbing a toe, excessive wetness, either from perspiration or application of ointments or creams, or improper cutting of nails If these factors come into play, the possibility increases that the nail edge can then penetrate the skin, just like a knife, and cause an infection. The skin at the nail edge becomes reddened and swollen. You may notice drainage or pus from the area and the pain becomes intolerable.</p>
                <h5>Treatment</p>
                <p>In the most minor cases, a simple removal of the nail margin is done. This affords considerable relief, but is temporary. In cases where the nail has grown in repeatedly, or when this becomes a chronic problem, a minor procedure called a Matrixsectomy. The podiatrist will gently numb your toe, reshape the nail edge and finally, apply a medicine which will, in most cases, permanently prevent the nail edge from growing improperly again.</p>
                <h5>Prevention</p>
                <p>Cutting toe nails properly goes a long way toward the prevention of ingrown nails. Cut the nails STRAIGHT ACROSS, so that the nail corner is visible. If you cut the nail too short so that the nail corner is not visible, you are inviting the nail corner to grow into the skin. It is the natural tendency, when the edge of the nail starts to grow in, to cut down at an angle at the nail edge, to relieve the pain. This DOES relieve he pain TEMPORARILY, but it also starts the downward spiral, training the nail to become more and more ingrown.</p>
              </div>
          </article>

          <hr/>
          <a name="skeletal"></a>
          <h2>Skeletal Foot Care</h2>
          <hr/>
          <!-- HeelSpur -->
          <article>
            <h3><a name="HeelSpur" data-magellan-destination="HeelSpur"></a>HeelSpur</h3>
            <div class="large-12 columns">
              <h5>Heel Spur, Plantar Fasciitis</h5>
              <p><img src="/1/images/pic004.gif" width="200" height="190" align="right">Typical symptoms are a dull ache most of the time, but when the patient first gets out of the bed in the morning, or when getting up after sitting for a period of time during the day, the pain in the heel is impressive. It almost feels like the heel has been bruised, from falling on a rock barefoot, but it is worse. Since there are several causes for heel pain, we need to pin-point the exact location of the pain is in order to diagnose the basic underlying cause for the problem. Testing is simple and generally pain-free. It's important to find out WHERE it hurts, not just HOW MUCH it hurts. After excluding general medical conditions that might cause the condition, the exam is localized to the heel and surrounding structures. The important anatomical structures are the heel bone (calcaneus), the tissues that attach to the bottom of the heel (plantar fascia) and the nerves that pass from the leg into the bottom of the foot (posterior tibial nerve and its branches). The exam begins with an assessment of the blood vessels and nerves that end in the foot because blood and nerve supply affect treatment.</p>
              <h5>Etiology</h5>
              <p>There is a tight ligament (band of fibrous tissue) that stretches across the arch, from the ball of the foot to the heel bone, called the Plantar Fascia. When we walk, our feet have a tendency to roll inward, toward each other, in a motion that we call pronation. When feet pronate, they flatten, stretch out and the arch elongates. This causes excessive pulling on the Plantar Fascia ligament and attachment of the ligament to the heel bone begins to separate. An injury occurs where the ligament progressively tears off of the heel, fiber by fiber. Bleeding occurs next to the bone and inflammatory fluids accumulate between the ligament and the bone, forming a Bursitis, or fluid-filled sack. Over time, the body lays down scar tissue, in an attempt to "glue" the detached ligament fibers back on to the bottom of the heel bone. Over the course of 3-5 years, the scar tissue calcifies, and this calcium deposit eventually becomes visible on X-Ray as the Heel Spur. This inflammation of this Plantar fascia ligament is called Plantar Fasciitis, and in addition to the Bursitis, is what causes the pain. The bone spur itself has no nerve endings and doesn't hurt. It is just an associated finding that tells us that the inflammatory process, the Bursitis and Plantar Fasciitis have been present for a long time. There are several reasons that this chronic injury can occur. Recent weight gain and increased activity level often start an episode. A change of shoes from well supporting walking or athletic shoes to floppy sandals can do it. When the arch of the foot collapses or flattens, the Plantar Fascia is stretched, causing the injury where it attaches to the heel bone. Finally, conditions which cause generalized increased inflammation, like osteoarthritis or rheumatoid arthritis can cause this. There is one more, smaller category of patients, who have heel pain due solely due to a loss of the protective fat pad cushion on the bottom of the heel. We rely on the Heel Fat Pad, that marvelous structure, to cushion our heel, like the sole of a good running shoe does, from the impact that a modern human body makes when it lands on it. A thinned Heel Fat Pad permits bruising, as our body weight is born by a much smaller, bony-hard and more concentrated area.</p>
              <h5>Treatment</h5>
              <p>It is better to rest the heel as much as practicable. When you are off your feet, the injury is healing and getting better. When you are standing, without any foot support, the heel is getting injured further. When you are standing when wearing orthotics (foot supports) and well supportive shoes, the injury decreases dramatically, but usually is not eliminated altogether. So, during the treatment period, if you have the choice of sitting or standing, sit ! If there are no health reasons to avoid them, a week's use of an over-the-counter anti-inflammatory medication may eliminate the pain. First, we need to protect the bone from the pulling of the plantar fascia. We do this by using some kind of in-shoe arch supporting device - an orthotic. They come in pairs, one for each foot. Next, we encourage the patient to stretch the tissue on the bottom of the foot. Three times a day, sit erect with the legs extended and loop a belt, scarf or towel around the forefoot. Pull the forefoot toward the upper leg. Expect to feel a mild pulling sensation at the back of the leg and in the arch. Stretching should not be done to the point of pain. This position is held for 30 seconds, and is repeated 3 times. The 3 repetitions at 30 seconds, 3 times-a-day is easy to remember.</p>
              <p>Because of the risk of stomach upset, non-cortisone anti-inflammatory medication can only be used for some patients and only for about one week. With a good response to the medication, it is a good idea to taper off over the next several days so as to avoid an abrupt rebound of pain.</p>
              <p>In addition to the above, we begin an aggressive course of physical therapy and cortisone injections. For physical therapy, the doctor may employ ultrasound, galvanic stimulation or any of a number of anti-inflammatory modalities in the office or at the offices of a physical therapist. The most effective way for physical therapy to work is if it is applied regularly, at least three times a week.</p>
              <p>Cortisone injections are usually done at weekly intervals, and most cases require 1-3 injections. The skin can be desensitized before the injection with a cold freezing spray designed to provide brief anesthesia. The injection is done from the inner side of the heel, not from the bottom. It is helpful to strap the arch with tape combined with an arch pad. This serves as a temporary simulation of the support that an Orthotic will provide on a more permanent basis. These measures will eliminate the problem in about 85% of patients within 3 weeks. Some get better quickly, others take the full 3 weeks.</p>
              <p>Surgery becomes necessary for the few who do not benefit from treatment. Heel spur removal is done only in the rare instance where the bony projection is directed downwards.</p>
            </div>
          </article>

          <hr/>
          <!-- Orthotics -->
          <article>
            <h3><a name="Orthotics" data-magellan-destination="Orthotics"></a>Orthotics</h3>
              <div class="large-12 columns">
                <h5>Description</h5>
                <p>Orthosis (Orthotics) is an in-shoe brace which is designed to correct for abnormal foot and lower extremity function [the lower extremity includes the foot, ankle, leg, knee, thigh and hip]. In correcting abnormal foot and lower extremity function, the prescription foot orthosis reduces the strain on injured structures in the foot and lower extremity, allowing them to heal and become non-painful. In addition, prescription foot orthoses help prevent future problems from occurring in the foot and lower extremity by reducing abnormal or pathological forces acting on the foot and lower extremity. A prescription foot orthosis is more commonly known by the public as a "foot orthotic".</p>
                <p>Two main types of foot orthoses. Accommodative orthoses and functional foot orthoses. Both types of prescription foot orthoses are used to correct the foot plant of the patient so that the pain in their foot or lower extremity will improve so that normal activities can be resumed without pain. However, accommodative and functional foot orthoses are generally made using different materials and may not look or feel the same. Both types of prescription foot orthoses are nearly always prescribed as a pair to allow more normal function of both feet [similar to having both the left and right wheels of a car realigned in a front end alignment].</p>
                <h5>Accommodative Foot Orthoses</h5>
                <p>Accommodative foot orthoses are used to cushion, pad or relieve pressure from a painful or injured area on the bottom of the foot. They may also be designed to try to control abnormal function of the foot. Accommodative orthoses may be made of a wide range of materials such as cork, leather, plastic foams, and rubber materials. They are generally more flexible and soft than functional foot orthoses. Accommodative orthoses are fabricated from a three dimensional model of the foot which may be made by taking a plaster mold of the foot, stepping into a box of compressible foam, or scanning the foot with a mechanical or optical scanner.</p>
                <p>Accommodative orthoses are useful in the treatment of painful callouses on the bottom of the foot, diabetic foot ulcerations, sore bones on the bottom of the foot and other types of foot pathology. The advantages of accommodative orthoses are that they are relatively soft and forgiving and are generally easy to adjust in shape after they are dispensed to the patient to improve comfort. The disadvantages of accommodative orthoses are that they are relatively bulky, have relatively poor durability, and often need frequent adjustments to allow them to continue working properly.</p>
                <h5>Functional Foot Orthoses</h5>
                <img algin="right" src="../img/orthotics.jpg"/>
                <p>Functional foot orthoses are used to correct abnormal foot function and, in so doing, also correct for abnormal lower extremity function. Some types of functional foot orthoses may also be designed to accommodate painful areas on the bottoms of the foot, just like accommodative foot orthoses. Functional foot orthoses may be made of flexible, semi-rigid or rigid plastic or graphite materials. They are relatively thin and easily fit into most types of shoes. They are fabricated from a three dimensional model of the foot which may be made by taking a plaster mold of the foot, stepping into a box of compressible foam, or scanning the foot with a mechanical or optical scanner.</p>
                <p>Functional foot orthoses are useful in the treatment of a very wide range of painful conditions of the foot and lower extremities. Big toe joint and lesser toe joint pain, arch and instep pain, ankle pain and heel pain are commonly treated with functional foot orthoses. Since abnormal foot function causes abnormal leg, knee and hip function, then functional foot orthoses are commonly also used to treat painful tendinitis and bursitis conditions in the ankle, knee and hip, in addition to shin splints in the legs. The advantages of functional foot orthoses are that they are relatively durable, infrequently require adjustments and more likely to fit into standard shoes. The disadvantages are that they are relatively difficult to adjust and relatively firm and less cushiony.</p>
                <h5>Foot and Lower Extremity Biomechanics</h5>
                <p>The study of the mechanical nature of the foot and lower extremity is called biomechanics. It is a specialized branch of science that uses the mechanical principles of physics to study the motions and forces on the human body. Podiatrists receive specialized, in-depth training during their four years of medical training on how the movements and forces in the foot affect the movements and forces in the rest of the lower extremity, and how the movements and forces in the lower extremity affect the movements and forces in the foot. No other medical specialty has this in-depth training, which is necessary to understand lower extremity pathology as it relates to the biomechanics of foot function. Therefore, the podiatrist is the most qualified medical specialist to diagnose and treat foot pathology.</p>
                <p>Understanding the biomechanics of the foot and lower extremity is of critical importance when the mechanism of an injury must be determined to decide on a appropriate treatment plan for the patient. In addition, biomechanics plays an important part in the planning for corrective surgery for injuries, such as tendon ruptures or bone fractures, or for the surgical correction of deformities of the foot, such as hammertoes, bunions, or heel spurs. As a result of the podiatrist's training and expertise in biomechanics, they will often prescribe either functional or accommodative orthoses as part of their treatment plan. In many instances, an orthosis will be all that is required for the successful treatment of foot or lower extremity pathology. In most instances, however, an orthosis will be prescribed along with other therapies, such as stretching or strengthening exercises, oral or injectable medications, and specific types of shoes, in order to insure the fastest healing for the patient.</p>
                <h5>The Process of Prescribing Foot Orthoses</h5>
                <p>In order to design and fabricate a prescription foot orthosis, the podiatrist must perform a biomechanical examination of the foot and lower extremities. Angular measurements are taken of the toes, foot, ankle, knees and hip to determine the amount and level of any structural or functional deformities. This examination is done while the patient is on an examining table and also while standing. The podiatrist will also do a walking and/or running gait analysis of the patient to determine how their foot and lower extremity functions during these activities. Abnormalities from the biomechanical examination and gait examination are noted in the patient's chart for future consideration in the design and fabrication of the prescription foot orthosis.</p>
                <p>The podiatrist then next must make a three dimensional model of the patient's feet in order to make a prescription foot orthosis. This is done by either applying plaster splints to the patient's foot, by having the patient step into a box of compressible foam, or having the foot scanned by a mechanical or optical scanner. The resultant three-dimensional model of the foot is then used along with a detailed orthosis prescription from the podiatrist to have the prescription foot orthoses made for the patient. Most podiatrists have a specialty podiatric orthosis laboratory make their orthoses while some podiatrists make their own prescription foot orthoses.</p>
                <h5>Advantages and Disadvantages of Prescription Foot Orthoses</h5>
                <p>The advantages of prescription foot orthoses are many. First of all, they are custom made for each foot of each patient, so that each foot orthosis will only fit one foot correctly. In addition, since they fit so exactly to the persons foot, they can be made with relatively rigid, durable materials with a minimal chance of discomfort or irritation to the patients foot. Prescription foot orthoses also have a much greater potential to effectively and permanently treat painful conditions, all the way from the toes to the lower back, since they are designed specifically for an individual's biomechanical nature.</p>
                <p>For example, in children, prescription foot orthoses are used to prevent abnormal development of the foot due to flatfoot or intoeing or outtoeing disorders. In athletes, prescription foot orthoses are used to allow the athlete to continue training and competing without pain. And in most adult patients, prescription foot orthoses are used to allow more normal daily activities without pain or disability.</p>
                <p>One disadvantage to prescription foot orthoses is that they are relatively expensive when compared to store bought over-the-counter foot inserts. Even though the over-the-counter inserts do help some people with mild symptoms, they do not have the potential to correct the wide range of symptoms that prescription foot orthoses can since they are made to fit a person with an "average" foot shape.</p>
                <p>In this fashion, prescription foot orthoses may be considered to be analogous to prescription eyeglasses. Over-the-counter eyeglasses may work for some people since they are made to correct for the average eye. However, over-the-counter eyeglasses will almost never work as well as prescription eyeglasses. Prescription foot orthoses, since they are custom made to each foot of a patient, are almost always more corrective and comfortable than over-the-counter foot inserts, even though over-the-counter inserts do work for some people.</p>
              </div>
          </article>

          <hr/>
          <!-- Tendonitis -->
          <article>
            <h3><a name="Tendonitis" data-magellan-destination="Tendonitis"></a>Tendonitis</h3>
              <div class="large-12 columns">
                <p>Tendonitis is inflammation of a tendon, the structure that connects a muscle to its bone. There are several tendons in the foot and ankle that are commonly affected. The inflammation can occur after trauma, from overuse, or as a result of another medical problem such as arthritis or collagen vascular diseases. The inflammation puts pressure on the surrounding nerves, causing pain, and releases certain chemicals that damage the tendon, causing further pain and sometimes altering the structure of the tendon.</p>
                <p>Most patients feel an aching pain in the area of the inflammation. There may also be swelling and/or weakness of the involved tendon. The pain usually increases with an increase in activity levels.</p>
                <h5>Cause</h5>
                <p>There are a number of ways that tendonitis may develop. A common cause is overuse, usually occurring after an increase in your activity level, or from improper or inadequate stretching before a work out. There are several tendons in the foot that act as a pulley when they round the ankle joint. Improper or excess motion in the tendon around the joint it may create tiny tears in the tendon, which triggers the inflammation that causes the pain. Tendonitis may follow trauma, such as ankle sprains, or may be the result of a medical problem such as arthritis.</p>
                <p>Another common cause is bio-mechanical fault. Excessive pronation or supernation can cause a muscle imbalance that may lead to inflammatory response of the tendon.</p>
                <h5>Treatment</h5>
                <p>In most cases, applying ice and taking Tylenol, or non-steroidal anti-inflammatory medication will relieve the pain. Keeping the foot elevated, decreasing your activity level for a couple of days, and wearing a compressive dressing such as an ace wrap will also help a great deal.</p>
                <p>If the pain continues, your doctor may send you for physical therapy, such as contrast bathes, ultrasound, massage, electrical stimulation, and/or stretching and strengthening exercises. Your may need to start wearing orthotics. If the problem is being caused by an underlying medical condition, your doctor may send you to a general practitioner or other medical specialist for treatment of that condition. In more severe cases, the tendon may need to be surgically repaired.</p>
                <p>The best way to prevent tendonitis is to stretch properly before any work out or athletic event. Wear high quality, supportive shoes that are made for your specific foot type. If you have been prescribed orthotics, wear them as directed. If you have an underlying medical problem that may cause tendonitis, follow the treatment plan for that condition. Finally, keep in good communication with your doctor so that if a problem arises, it can be treated quickly and accurately. </p>
               </div>
          </article>

          <hr/>
          <!-- Arthritis -->
          <article>
            <h3><a name="Arthritis" data-magellan-destination="Arthritis"></a>Arthritis</h3>
              <div class="large-12 columns">
                <p>Arthritis is a condition that slowly wears away joint. It is the leading cause of physical disability in the United States , affecting millions of Americans. Although it can affect any joint, it usually first shows up in the feet. Symptoms are joint swelling, pain (especially on movement), tenderness, heat and morning stiffness. Over time as the joint lining (cartilage) breaks down, the bones rub against each other causing pain and development of bone spurs. This reduces the range of motion of the joint causing a difficulty in walking. Arthritis is a condition that is believed to be hereditary, but can also be induced by injuries, drugs, bacteria and viral infections of the joint.</p>
                <h5>Common Types of Arthritis</h5>
                <h5>Osteoarthritis</h5>
                <p>this is the most common form of arthritis and afflict virtually everyone to some degree after the age of 60. It is also known as degenerative arthritis because it causes a breakdown of cartilage and bone. This causes pain, stiffness and muscle weakness. Any condition that puts increased stress on the joints such as weight gain, repetitive joint motion and injury can trigger osteoarthritis.</p>
                <h5>Rheumatoid arthritis</h5>
                <p>This is a syndrome of diseases with a wide variety of symptoms that can affect the entire body. In its most serious or advanced form it causes a joint destruction and crippling joint deviation. In rheumatoid arthritis, the immune system turns against itself. Instead of protecting the body, it destroys the joints. It frequently affects joints in a symmetrical pattern. Symptoms can include morning stiffness, weight loss, slight fever and joint deformity. Women are more likely to develop rheumatoid arthritis than men</p>
                <h5>Gouty arthritis</h5>
                <p>This is condition caused by a build up of Uric Acid in the joints. Uric acid is a waste product that is usually dissolved in the blood and passes into the urine through the kidneys. In Gouty arthritis of Gout, the uric acid changes into crystals that form deposits in the joints and other tissue. This causes severe pain and swelling in the joint. Gout usually affects the big toe and afflicts men more often than women. Used to be called the rich men's disease, it may be precipitated by eating red meat, rich sauces and alcohol available in the old days to the rich only.</p>
                <h5>Treatment</h5>
                <p>Most forms of arthritis can not be cured, they can be controlled. If your symptoms are mild, medications may be enough to control the pain and swelling. Relieving the pain, controlling the inflammation and preserving or restoring joint movement and functions are the goals of any treatment program. For more severe arthritis, surgery may be needed to accomplish those goals. Living comfortably with arthritis requires both rest and exercise. Shoe inserts ( Orthotics) my help with improving foot function, and reduce pain. Good shoes may be helpful in accommodating the joint deformities as well.</p>
              </div>
          </article>

          <hr/>

          <a name="surgical"></a>
          <h2>Surgical Foot Care</h2>
          <hr/>
          <!-- Neuroma -->
          <article>
            <h3><a name="Neuroma" data-magellan-destination="Neuroma"></a>Neuroma</h3>
              <div class="large-12 columns">
                <p>A neuroma is a swelling or scarring of a small nerve that connects to two of your toes and provides sensation to these toes. The symptoms can come and go depending on activity, shoe style and even, weather. They consist of pain or numbness, usually affecting the 3rd and 4th toes at the third interspace. Any action that shifts the body weight onto the front of the foot, such as wearing high heels, climbing stairs and running, can make a neuroma worse. It is an injury to a nerve that occurs slowly, over a long period of time. <img algin="right" src="../img/neuroma.jpg"/></p>
                <h5>Symptons</h5>
                <p>Neuromas frequently start as a numbness or tenderness in the ball of the foot. This is the area just behind the base of the toes. As the swelling increases, shooting pain and strange sensations such as numbness, burning and tingling in the area can radiate out into the toes or back into the foot. The area may be hot or very swollen and, just as mysteriously, the symptoms can disappear and reappear. At first, the pain is only present when weight bearing in tight shoes. As it gets worse, spontaneous shooting pains, often like electric shocks, can be felt even when you're off your feet.</p>
                <h5>Etiology</h5>
                <p>To understand why neuromas develop, it is important to know how the nerves connect to the toes. The nerve that carries sensation signals back from the toes starts in the midfoot between the metatarsals. The nerve passes beneath a strong ligament, or soft-tissue band, that holds the metatarsal heads together. Just after it passes this band, it splits in half forming a Y. Each half then connects to the adjacent sides of the two toes.</p>
                <p>The neuroma usually develops just under or beyond the tight ligament. The constant pulling of nerve over the ligament irritates the nerve and causes the nerve to thicken and scar. The nerve also can get pinched between the two metatarsal bones that it passes between. A scarred nerve doesn't carry signals well and may send back strange signals to the brain such as burning, pain and tingling. So, instead of beautiful music, we get terrible noise.</p>
                <p>Anything that stretches and pulls the nerve will aggravate the condition. For instance, wearing high heels aggravates neuromas in three ways. First, the higher heel will push the toes up from the rest of the foot and cause the nerve to tighten and pull harder against the tight ligament. Second, the tight toe box squeezes the front of the foot together leaving less space between the metatarsal bones for the nerve to rest. Finally, the body weight is put more on the ball of the foot increasing the pressure on the nerve. All 3 are bad news for you and your neuroma.</p>
                <h5>Treatment</h5>
                <p>After the diagnosis is made, the doctor may apply special padding to the foot to take the pressure off the area. An injection of an anti-inflammatory medicine (cortisone) mixed with numbing medicine (xylocaine) may be put into the area surrounding the nerve to calm it down. The doctor may also prescribe a prescription anti-inflammatory medication.</p>
                <p>If these treatments are not effective at calming the neuroma down, orthotics may be prescribed to help control the abnormal mechanical structure of your foot. By preventing the arch from dropping, the nerve will not be stretched as much.</p>
                <p>Finally, if these more conservative treatments don't work, then the faulty nerve may need to be removed. This is only a sensory nerve that doesn't control any muscles and only provides sensation to a small area between the toes. The nerve is removed through an incision in the top or bottom of the affected area. The nerve is identified and snipped just behind the swollen part and just beyond where it splits in two. Frequently, the tight ligament between the metatarsal bones is also cut to allow more room. It is a relatively minor procedure.</p>
                <p>Another procedure involves the destruction of the sensitive nerve through the injection of caustic medications. Either way, the area between the affected toes is likely to remain numb forever. However, this is rarely more than a minor annoyance.</p>
             </div>
          </article>

          <hr/>
          <!-- Bunion -->
          <article>
            <h3><a name="Bunion" data-magellan-destination="Bunion"></a>Bunion</h3>
              <div class="large-12 columns">
                <h5>Description</h5>
                <p>One of the more common conditions treated by podiatric surgeons is the painful bunion. Patients with this condition will usually complain of pain when wearing certain shoes, especially snug fitting dress shoes, or with physical activity, such as walking or running. Bunions are most commonly treated by conservative means. This may involve shoe gear modification, padding and <a href="http://www.podiatrynetwork.com/document_disorders.cfm?id=148" target="_blank">orthoses </a>. When this fails to provide adequate relief, surgery is often recommended. There are several surgical procedures to correct bunions. Selection of the most appropriate procedure for each patient requires knowledge of the level of deformity, review of the x-rays and an open discussion of the goals of the surgical procedure. Almost all surgical procedures require cutting and repositioning the first <strong>metatarsal</strong>.</p>
                <h5>Cause of Bunion Deformity</h5>
                <p>The classic bunion, medically known as <strong>hallux abducto valgus</strong> or <strong>HAV</strong>, is a bump on the side of the great toe joint. This bump represents an actual deviation of the 1st metatarsal and often an overgrowth of bone on the metatarsal head. In addition, there is also deviation of the great toe toward the second toe. In severe cases, the great toe can either lie above or below the second toe. Shoes are often blamed for creating these problems. This, however, is inaccurate. It has been noted that primitive tribes where going barefoot is the norm will also develop bunions. Bunions develop from abnormal foot structure and bio-mechanics (e.g. excessive <strong>pronation</strong>), which place an undue load on the 1st metatarsal. This leads to stretching of supporting soft tissue structures such as joint capsules and ligaments with the end result being gradual deviation of the 1st metatarsal. As the deformity increases, there is an abnormal pull of certain tendons, which leads to the drifting of the great toe toward the 2nd toe. At this stage, there is also adaptation of the joint itself that occurs. Bunions tend to be familial but not hereditary.</p>
                <h5>Symptoms Related to Bunion Deformity</h5>
                <p>The most common symptoms associated with this condition are pain on the side of the foot. Shoes will typically aggravate bunions. Stiff leather shoes or shoes with a tapered <strong>toe box</strong> are the prime offenders. This is why bunion pain is most common in women whose shoes have a pointed toe box. The bunion site will often be slightly swollen and red from the constant rubbing and irritation of a shoe. Occasionally, corns can develop between the 1st and 2nd toe from the pressure the toes rubbing against each other. On rare occasions, the joint itself can be acutely inflamed from the development of a sac of fluid over the bunion called a bursa. This is designed to protect and cushion the bone. However, it can become acutely inflamed, a condition referred to as <strong>bursitis.</strong></p>
                <h5>Treatment of Bunion Deformity</p>
                <p>Early treatment of bunions is centered on providing symptomatic relief. Switching to a shoe with a rounder, deeper toe box and made of a softer more pliable leather will often provide immediate relief. The use of pads and cushions to reduce the pressure over the bone can also be helpful for mild bunion deformities. Controlling abnormal pronation, by the use of Orthotics and ther by reduces the deforming forces leading to bunions in the first place is usually the initial treatment of choice. These may help reduce pain in mild bunion deformities and slow the to provided adequate relief, surgical correction is indicated. The choice of surgical procedures (<strong>bunionectomy</strong>) is based on a biomechanical and radiographic examination of the foot. Because there is actual bone displacement and joint adaptation, most successful bunionectomies require cutting and realigning the 1st metatarsal (an <strong>osteotomy</strong>). Simply "shaving the bump" is often inadequate in providing long-term relief of symptoms and in some cases can actually cause the bunion to progress faster. The most common procedure performed for the correction of bunions is the osteotomy near the level of the joint.</p>
              </div>
          </article>

          <hr/>
          <!-- Hammertoes -->
          <article>
            <h3><a name="Hammertoes" data-magellan-destination="Hammertoes"></a>Hammertoes</h3>
              <div class="large-12 columns">
                <h5>Symptons</h5>
                <p>Hammertoe is the general term used to describe an abnormal contraction or "buckling" of the toe because of a partial or complete dislocation of one of the joints of the toe or the joint where the toe joins with the rest of the foot. As the toe becomes deformed, it rubs against the shoe and the irritation causes the body to build up more and thicker skin to help protect the area. The common name for the thicker skin is a corn. At first, this thick skin helps reduce irritation to the bone prominence, but as the skin becomes thicker, it adds to the pressure from the shoe. Periodic trimming of the corn may give temporary relief. However, over a period of time, a bursa may develop and if it becomes inflamed (bursitis), the area becomes red, swollen and painful. It may also become infected.</p>
                <img algin="right" src="../img/hammertoe.jpg"/>
                <p>There are two joints in the lesser toes and one joint in the great toe. If the deformity occurs in the joint nearest the nail, it is called a mallet toe and the corn will usually develop on the tip of the toe. This is due to the pressure being on the tip of the last toe bone rather than at the fat pad under the tip of the toe. If the deformity is at the other toe joint, or where the toe joins the foot, it is called a hammertoe and the corn will occur on the top of the toe. Corns may also develop between toes. These are usually due to a rotation of the toe, rather than a contraction (buckling). This can cause the joints to rub together and may create small bone spurs that cause corns in a similar manner. Do not confuse corns with calluses that occur on the bottom of the feet. They are generally caused by other conditions, although a severe hammertoe may create downward pressure on a metatarsal bone at the ball of the foot, and add to the cause of a callus.</p>
                <h5>Causes</h5>
                <p>Although there is little doubt shoes are responsible for causing corns, the size, shape and other characteristics of our feet are hereditary. The contraction and/or rotation of toes can be the result of poor mechanics of the foot, resulting in over-pronation. This results in low or flat arches, which cause the muscles and tendons of the foot to twist the toes and joints away from their normal position. High arched feet can also result in similar conditions. A severe bunion may cause a hammertoe, as the great toe twists over or under the second toe, causing it to dislocate. Shoes cause the corn, as the bony top of the toe rubs on the toe box of the shoe, but the underlying problem is the abnormal position of the toe joints, which may be hereditary. The crooked toe is irritated by shoe pressure on the joint or spur. As a result, the skin becomes thicker to form a protection. The thicker the skin, the more pressure and eventually, a bursitis under the corn may develop. This causes the joint to become red, swollen and painful. Additionally, the skin can break down and become infected.</p>
                <h5>Treatment</h5>
                <p>The most important thing is to purchase well fitted, comfortable, low heeled shoes that do not irritate the crooked toe. Also, make sure your stockings are not tight, causing the toes to contract. High heel shoes should be worn at a minimum, as they cause the tendons of the toes to pull them up into an contracted position. Tennis type and walking shoes have significantly decreased the complaint of many people with hammertoe deformities. Although the crooked toe is still present, it may not hurt if the shoe is large enough. <strong>BATHTUB SURGERY IS NOT A GOOD IDEA!</strong> Trimming corns with a razor blade may give temporary relief, but is dangerous, as you can cut yourself and cause an infection. Non-medicated pads from the drug store do give relieve from shoe pressure and are helpful. However, if the toe becomes red and swollen, consult with your family podiatrist right away. Treatment may range from more appropriate footgear to periodic trimming and padding of the corn. Cortisone injections may be indicated if a bursitis is present. Removable accommodative pads may be made for you. If conservative treatment is unsuccessful, surgical intervention may be suggested. In the early stages, when the toe joints are flexible. If the toe is relatively straight and the corn is caused by pressure on a spur, the enlarged bone may be remodeled and the spur removed. In more advanced cases, when the joint is dislocated, part of the bone at the joint may be removed. Most of these toe surgeries can be performed in the office or the outpatient surgery under local anesthesia. Sometimes you can wear sandals after surgery and other times, a special stiff soled shoe is used so you can walk right away.</p>
              </div>
          </article>
        </div>

        <aside class="large-3 columns">
          <nav id="side-nav" data-magellan-expedition="">
            <h5>External Foot Care</h5>
            <ul class="side-nav">
              <li><a href="#AthleteFoot" data-magellan-arrival="AthleteFoot">Athlete's Foot</a></li>
              <li><a href="#FungusNails" data-magellan-arrival="FungusNails">Fungus Nails</a></li>
              <li><a href="#PlantarWarts" data-magellan-arrival="PlantarWarts">Plantar Warts</a></li>
              <li><a href="#Ulcers" data-magellan-arrival="Ulcers">Ulcers</a></li>
              <li><a href="#CornsCalluses" data-magellan-arrival="CornsCalluses">Corns & Calluses</a></li>
            </ul>
            <h5>Internal Foot Care</h5>
            <ul class="side-nav">
              <li><a href="#HeelSpur" data-magellan-arrival="HeelSpur">Heel Spur, Plantar Fascitis</a></li>
              <li><a href="#IngrownToenails" data-magellan-arrival="IngrownToenails">Ingrown Toenail</a></li>
              <li><a href="#Orthotics" data-magellan-arrival="Orthotics">Orthotics</a></li>
              <li><a href="#Tendonitis" data-magellan-arrival="Tendonitis">Tendonitis</a></li>
              <li><a href="#Arthritis" data-magellan-arrival="Arthritis">Arthritis</a></li>
            </ul>
            <h5>Surgical Foot Care</h5>
            <ul class="side-nav">
              <li><a href="#Neuroma" data-magellan-arrival="Neuroma">Neuroma</a></li>
              <li><a href="#Bunion" data-magellan-arrival="Bunion">Bunion</a></li>
              <li><a href="#Hammertoes" data-magellan-arrival="Hammertoes">Hammertoes</a></li>
            </ul>
          </nav>
          <div class="panel">
            <h5>Featured</h5>
            <p>Anything you want to highlight/feature here?</p>
            <a href="#">Read More →</a>
          </div>
        </aside>
        <script>
          $(function() {
            var stickyHeight = $('aside').height();

            $(window).scroll(function(){
              var windowTop = $(window).scrollTop();
              if(stickyHeight < windowTop){
                $('#side-nav').css({position: 'fixed', top: 0, marginTop: '45px'});
              }else{
                $('#side-nav').css({position: 'relative'});
              }
            });
            $('a').click(function(){
              $('html, body').animate({
                scrollTop: ($('[name="' + $.attr(this, 'href').substr(1) + '"]').offset().top ) - 45
              }, 500);
              return false;
            });
            $.fn.foundationMagellan
          });
        </script>
      </div>
<?php include('../footer.php');?>
